### ISSUE TITLE
Unable to plant seeds when using TenPlus1 farming mod

### ISSUE THREAD

**Issue by Fixer-007** [ac-minetest/basic_machines#1]
This problem occurred on ESM City when TenPlus1 farming mod was installed, now my autofarming machine located behind the house is planting the seeds as usual... but they are not growing, just hanging in the air endlessly.

**Comment by ac-minetest** [comment]
thats because tenplus1 farming mod starts growing seed after it was placed by player only.. by hand

**Comment by ac-minetest** [comment]
fixed now: you can use dig mode and take seed from chest, they will automatically transform into corresponding plants that just start growth

**Comment by Fixer-007** [comment]
Is it already on ESM? I can't get it to work.
