### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by cyian-1756** [ac-minetest/basic_machines#2]
The repo should have a readme that outlines what the mod does

**Comment by cyian-1756** [comment]
Never mind you use a wiki

**Comment by SmallJoker** [comment]
Please re-open: Not everybody might see that there's a wiki about this mod.

**Comment by Fixer-007** [comment]
I agree, please add readme and tutorial, mod users will appreciate.

**Comment by cyian-1756** [comment]
Issue reopened

**Comment by ac-minetest** [comment]
added readme with link to wiki and hint to ingame help
