### ISSUE TITLE
Clockgen ABM has an impossible "neighbors" condition

### ISSUE THREAD

**Issue by FaceDeer** [ac-minetest/basic_machines#21]
[the "neighbors" definition for the clockgen ABM](https://github.com/ac-minetest/basic_machines/blob/086871b65f8737daad0441167228966ff77be72c/mover.lua#L1425) causes the ABM to only run when a node named "" (the empty string) is adjacent. I think you meant to have a table with no contents at all instead, which causes the ABM to run regardless of neighbors.

**Comment by neoh4x0r** [comment]
@FaceDeer 
This allows affects the power crystal generator.

I think `neighbors = {""},` can just be removed.

**Comment by ac-minetest** [comment]
it works well, what exactly is the problem?
