### ISSUE TITLE
Overheating

### ISSUE THREAD

**Issue by za267** [ac-minetest/basic_machines#29]
Hi - This isn't really an issue but I've been trying to figure out how overheating works with basic_machines. I couldn't find much documentation about it.  I've got some machines that are constantly overheated even though they aren't really doing anything.

**Comment by ac-minetest** [comment]
overheating works simple:

if machine is activated it heats up, with time it cools down a little too (fixed rates). So if you activate too much temperature rises over limit and overheat happens.
