### ISSUE TITLE
Grinder removal

### ISSUE THREAD

**Issue by minertestdude** [ac-minetest/basic_machines#32]
Just removed Grinder and all in its update slot (Grinders) disappeared. Could be serious surprise for some players. Big thanks if its fixable (or not)!

PS
rip 3 grinders...

**Comment by ac-minetest** [comment]
This could be considered a fail on players side to check if its safe to dig. Question is, do we want players who are attentive or mindless zombies where everything is done for them :)

**Comment by minertestdude** [comment]
yes, but batteries, generators and movers also refuse removal if anything in upgrade slot. I think most players are unattentitive zombies anyway.

**Comment by berengma** [comment]
That was me who added security checks that other day. You do not feel like laughing when you accidently dig your generator with a stack of generator upgrades inside :)
I forgot the grinders though. Still cheap compared to generators I guess.

**Comment by minertestdude** [comment]
@berengma could I ask you to add grinder too? At 1.5 diamond block/4 mese block per grinder, potential to wipe substantial amount is present.

**Comment by berengma** [comment]
I would, but this is rnd's mod. not mine.
My fork of this isn't compatible anymore anyway, as I left out the vegetable thing.

It is pretty trivial to fix, besides.

**Comment by minertestdude** [comment]
I see.

PS
Aww, vegetable thing is beatutiful! I have now space farm in addition and break my head how to make detector-based farm. TL;DR - it takes some brain and time to make farm now, not just mining initial resource.
