### ISSUE TITLE
Improve DETECTOR help text in advanced section.

### ISSUE THREAD

**Issue by minertestdude** [ac-minetest/basic_machines#34]
Currently it reads:
´´´
ADVANCED: you can use distributor as an event handler. First you must deactivate first target by putting 0 at last place in first line. Meanings of first 2 numbers are as follows: first number 0/1 controls if node/nlistens to failed interact attempts around it, second number -1/1 listens to chat and can mute it
´´´

i suggest:
´´´
ADVANCED: Distributor can act as event handler - listen to events and actions of players above it.  For this first entry is configured in special way: assign MODE to 0, target X=0/1 controls monitoring of interaction attempts, target Y=-1/0/1 mutes, disables or enables chat monitoring. Such distributor will still accept normal external signals, in addition to monitoring functions.
´´´

RFC

**Comment by ac-minetest** [comment]
You have fallen in the same 'documentation' trap as me, 'what entry' ?
Its clear to you now but it won't be to others. Plus i had to read the rest 2x slowly to understand :)

Updated to:

SETUP: to select target nodes for activation click SET then click target node.
You can add more targets with ADD. To see where target node is click SHOW button next to it.
4 numbers in each row represent (from left to right) : first 3 numbers are target coordinates x y z,
last number (MODE) controls how signal is passed to target. For example, to only pass OFF signal use -2,
to only pass ON use 2, -1 negates the signal, 1 = pass original signal, 0 blocks signal
delay option adds delay to activations, in seconds. With negative delay activation is randomized with probability -delay/1000.

ADVANCED: you can use distributor as an event handler - it listens to events like interact attempts and chat around distributor.
First you need to place distributor at position (x,y,z) in world, such that the coordinates are of the form (20*i,20*j+1,20*k) for
some integers i,j,k. Then you need to configure first row of numbers in distributor:
by putting 0 as MODE it will start to listen. First number x = 0/1 controls if node listens to failed interact attempts around it, second
number y= -1/0/1 controls listening to chat (-1 additionaly mutes chat)
