### ISSUE TITLE
Mover+protection bug: no battery checking before acting

### ISSUE THREAD

**Issue by minertestdude** [ac-minetest/basic_machines#37]
You know it, because you demonstrated it. :)

Bug: 
Mover must check for battery in proximity first before operating.

Reproduce:
Place protection block,near mover, keypad.
Set mover to some "node"
Set keypad to mover position (push keypad, push mover)
Set keypad repeat 500

If other player walks into the node, then he will be rotated as if he tries to touch keypad (correct), but it shouldnt try to work, before checking battery in proximity.

**Comment by ac-minetest** [comment]
This is a feature caused by 'protector mod annoying players'. Machines mod just does a protector check before doing more stuff.

**Comment by minertestdude** [comment]
ok, thumbs up
