### ISSUE TITLE
New mithril recipe not working

### ISSUE THREAD

**Issue by minertestdude** [ac-minetest/basic_machines#39]
Right now on Bananaland, new mithril recipe is ignored. However Bananaland pulls latest mod version.

**Comment by minertestdude** [comment]
Same for silver. Both mithril and silver have old ingot-dust33-dust66-ingot scheme.

**Comment by ac-minetest** [comment]
This was all fixed in version 0527a

**Comment by minertestdude** [comment]
Fair enough.
