### ISSUE TITLE
feature 'request' basic_machines:clockgen showing owner

### ISSUE THREAD

**Issue by justtestrestoration** [ac-minetest/basic_machines#5]
When placing a basic_machines:clockgen it isn't obvious who owns it by looking at the node since it doesn't tell who placed it there. I and another player are building machines together and I wouldn't like to confuse that player(by re-placing the clockgen), who knows less about machines than I do, why the machines won't be working when that player is online and I'm offline.

Would you like such a feature to be implemented? If yes, then let me know and I'll attempt working on it(if you think it's a trivial thing to work on). 

Thanks

**Comment by ac-minetest** [comment]
feature added
