### ISSUE TITLE
autocrafter not crafting

### ISSUE THREAD

**Issue by taikedz** [ac-minetest/basic_machines#7]
Hello - just pulled latest from master

Autocrafter is not crafting

* placed autocrafter in world
* added 6 glass in a door formation
* preview shows glass door
* added 38 glass to the crafter
* no doors being produced

Are there new actions to be performed now or is there something I've missed? It looks like you removed the toggle button, as well as some code for starting timers, I was unable to unpick what is actually behind running the autocrafter now...

**Comment by hajo4** [comment]
Did you use a keypad to activate the autocrafter ?

**Comment by ac-minetest** [comment]
You need to activate every machine with signal or it wont work.

There are no background running actions ( = no lag for server) except slow activating clockgen ( clock generator ) or keypads with repeat set.
